server:
  port: 9999
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/reserve?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password:
  devtools: # 热部署
    livereload:
      enabled: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    static-path-pattern: classpath:/static/
mybatis-plus:
  type-aliases-package: com.yanzhen.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/yanzhen/dao/*.xml

